// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgiknrhcflnlgimvjzsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnaWtucmhjZmxubGdpbXZqenN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1Nzc5MDIsImV4cCI6MjA1OTE1MzkwMn0.Hs1N3h1aBZPmtb7HNL-2AmgSUf9CmSEPdwbRAxWPk4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);